const meta = {
    title: 'Hi, My name is Sheharzad Salahuddin',
    aboutText: 'About Me',
    designation: 'I am a Web Developer',
    description: 'Currently serving as a VueJS Front-End Developer at a technology firm in Lahore, this individual has enhanced user engagement and conversion rates through proficiency in Vue.js, JavaScript, and Bootstrap. Previously interning at a software development company, the focus was on developing secure digital payment systems and efficient data storage solutions using technologies like ReactJS, MongoDB, and PostgreSQL. With a strong foundation in software engineering, agile methodologies, and recognized for problem-solving skills, team collaboration, and ethical work practices.',
    projectTitle:'My Latest Project',
    getIn: 'Get in touch',
    Profile: 'View Profile',
    footerContent: '© 2022. All rights reserved by Sheharzad Salahuddin',
    Home: 'Home',
    About: 'About',
    Portfolio: 'Portfolio',
    Contact: 'Contact',
    Proficiency: 'Proficiency',
    Certifications: 'Certifications',
    Hire: 'Hire Me',
    Available: 'I am available for work.',
    Connect: 'Connect with me via Linkedin: ',
    SendMessage: 'Send a Message',
    WhatDoI: 'What I do',
    AppWeb: 'Develop highly interactive Front End / User Interfaces for your web and mobile applications',
    AppWeb2: 'Integration of third party services such as Firebase / Maps / Payment-Gateways',
    Certifications: 'Certifications',
    collaboration: 'Collaborated with marketing team to boost user engagement and conversion rates.',
    background: 'Strong background in software engineering and agile methodologies.',
    framework: 'Experienced with various development frameworks and technologies including ReactJS, MongoDB, PostgreSQL.',
}

export {meta} 